// File generated by Antigravity AI, representing standard Firebase configuration settings.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase projects.
///
/// To connect to your actual Firebase project, please update the placeholders
/// below (such as 'YOUR_API_KEY') with the real values from your Firebase Console settings.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Placeholder indicating whether the options are configured or still templates.
  static bool get isConfigured {
    // If the apiKey still matches the placeholder value, it is not configured.
    return android.apiKey != 'YOUR_ANDROID_API_KEY' &&
           web.apiKey != 'YOUR_WEB_API_KEY';
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZv9FQTPMFV-0landPgaOwtjivI9W_1qQ',
    appId: '1:622639751034:android:2f771264afaa3b037cc0c3',
    messagingSenderId: '622639751034',
    projectId: 'splitwise-3fcdd',
    storageBucket: 'splitwise-3fcdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.internship.splitwise.splitwise',
  );
}